### ISSUE TITLE
Access to models is not present

### ISSUE THREAD

**Issue by Iory1998** [heshengtao/comfyui_LLM_party#89]
**Describe the bug**
---> All loaders are missing the list to choose a model (see attached screen)
![image](https://github.com/user-attachments/assets/3e8332eb-dcbc-4f28-a5ab-960889925b79)

**To Reproduce**
1. Go to '...' --> Install the the custom nodes from the manager.
2. Click on '....' Search for any loader node
3. Try to choose the model from the model folder
4. There is no list. You have to paste the path to the model Itself

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser Chrome, Firefox, and Vivaldi

**Smartphone (please complete the following information):**

**Additional context**
Also, why is the seed not present in any sampler? That gives the same output no matter what temp I use.

**Comment by heshengtao** [comment]
For the first question, because the party pursues a very high degree of freedom, it is designed like this. The first text box of the loader node can not only enter the local absolute path, but also enter the repo id on the HF to directly pull the model. For users who download the model to another location, the party should not force these users to put the model under the comfyui path. You can even map the hard disk of other computers to this computer to load the model from another computer. Some users use NAS to save these large models. If you force the user to copy the model to the comfyui folder, the hard disk where the comfyui is located will eventually be unable to store it because there are too many models.


For the second problem, it has nothing to do with seed. Your dependency reported an error. This output is an error message. In order to fix this problem, you need to:

```python
Pip install --upgrade bitsandbytes
```
or
```python
Pip uninstall bitsandbytes
Pip install bitsandbytes
```

Attention! This installation operation needs to be performed in your comfyui environment. If you don't know how to enter the comfyui environment, you can write the command line like this:

```python
Path/to/python.exe -m pip install --upgrade bitsandbytes
```

`Path/to/python.exe` is the absolute path to your comfyui Python interpreter.

In addition, since Llama 3.2 is very new, you will most likely need to upgrade the transformer library in your comfyui environment to the latest.

```python
Path/to/python.exe -m pip install --upgrade transformer
```

**Comment by Iory1998** [comment]
Hello.
Thank you for your prompt reply. Much appreciated.

> For the first question, because the party pursues a very high degree of freedom, it is designed like this. The first text box of the loader node can not only enter the local absolute path, but also enter the repo id on the HF to directly pull the model. 

I understand the logic, but the way it's implemented right now is cumbersome if one has many models to test. I suggest that you add a new model loader that extract model list from a predefined model folder (models\LLM). User would still have the choice to change the default folder in the Config.ini file.

By the way, there is a custom node called ComfyUI VLM that has a loader that works with yours. Please refer to the screenshot. The issue is that this loader only works for GGUF models, unlike LLM party that offer a wider choice of loader nodes.

Please consider adding this feature ASAP.

As for my point on the Seed, kindly add a seed input because the way it works now, I always get the same response no matter what temperature I use.
Your custom nodes are awesome, but you can make them even better if you add the seed input and the model list in the loaders.

Also, how does the "auto get model list" node work?
![image](https://github.com/user-attachments/assets/6ada9cb4-c6aa-4aba-981e-d2d8f7b67de4)

**Comment by heshengtao** [comment]
The `auto get model list` node will get all the model lists in your proxy API according to the base URL and openai api key you wrote in config.ini, which is not applicable to the local model. I guess it will make a similar node for the local model to get the local model path as you said, so that users can freely enter any path and get the sub-folder paths of various models from the model folder.

**Comment by Iory1998** [comment]
> The `auto get model list` node will get all the model lists in your proxy API according to the base URL and openai api key you wrote in config.ini, which is not applicable to the local model. I guess it will make a similar node for the local model to get the local model path as you said, so that users can freely enter any path and get the sub-folder paths of various models from the model folder.

I see. Thank you for your quick reply, as always. I am a big fan of this project and I hope you keep up the good work.
